---
- name: Playbook to Print Hostname and List Root Directory
  hosts: all
  gather_facts: false
  tasks:
    - name: Print Hostname
      command: 
        cmd: echo $HOSTNAME 
        _uses_shell: true
      register: whoami_output

    - name: Display Who Am I Output
      debug:
        msg: "Whoami: {{ whoami_output.stdout }}"

    - name: Print the EE OS
      command: 
        cmd: cat /etc/os-release
        _uses_shell: true
      register: hostname_output

    - name: Display Hostname
      debug:
        msg: "Hostname: {{ hostname_output.stdout }}"        

    - name: List Directories in Root (/)
      command: 
        cmd: ls -ltra
        _uses_shell: true
      register: directories_output

    - name: Display Root Directories
      debug:
        msg: "{{ directories_output.stdout_lines }}"
