---
- name: Playbook to Print Hostname and List Root Directory
  hosts: all
  gather_facts: true
  tasks:
    - name: Print the Hostname
      command: 
        cmd: whoami
        _uses_shell: true
      register: hostname_output

    - name: Display Hostname Output
      debug:
        msg: "Hostname: {{ hostname_output.stdout }}"

    - name: List Directories in Root (/)
      command: 
        cmd: ls -d /*/
        _uses_shell: true
      register: directories_output

    - name: Display Root Directories
      debug:
        msg: "Root Directories:\n{{ directories_output.stdout_lines | join('\n') }}"
