---
- name: Playbook to Print Hostname and List Root Directory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print the Hostname
      command: hostname
      register: hostname_output

    - name: Display Hostname Output
      debug:
        msg: "Hostname: {{ hostname_output.stdout }}"

    - name: List Directories in Root (/)
      command: ls -d /*/
      register: directories_output

    - name: Display Root Directories
      debug:
        msg: "Root Directories:\n{{ directories_output.stdout_lines | join('\n') }}"
